### ISSUE TITLE
Request - Expand the extension to other browsers

### ISSUE THREAD

**Issue by Leo-MapCreator** [xenonsb/Haxball-Room-Extension#30]
Hi @xenonsb 
Is it possible to add this extension to other browsers? Im using Opera now and it doesnt exist there.
Opera and Chromium Edge both are based on Chrome, so i think it wouldn't be hard to expand the extension to other browsers

Thx in advance.

**Comment by xenonsb** [comment]
Hi, I've been slacking lately due to work :(

For Opera, that's a hard no - I've tried registering for a dev account there many months ago and they've still yet to approve my account. I've lost hope on that end

For Chromium Edge - you already can install the extension via the Chrome webstore! Simply go to about:extensions and enable "Allow extensions from other stores". For a quick guide, refer to here: https://pureinfotech.com/install-chrome-extension-chromium-edge/

**Comment by Leo-MapCreator** [comment]
Oh, i didn't know that, maybe they have forgotten about your account aproval among many others, can't you apply again? I would love to use that extension on this new browser im using, i think its way better and i would like to play haxball here instead of switching to Chrome because the extension only works there

**Comment by xenonsb** [comment]
I'm happy to hear about the positive feedback! Unfortunately I've just double checked the Opera panel and it doesn't allow for me to re-submit a different version to "remind" them about it. Deleting the add-on that I've submitted there also restricts me from resubmitting the add-on.

I have done some testing on Opera with the previous version of the add-on - at that time even, many features didn't work because the API support was different. I'm afraid that'll be it for now on Opera's front :(

**Comment by Leo-MapCreator** [comment]
:((((

**Comment by xenonsb** [comment]
Hey @Leo-MapCreator, sorry to revive this - although there's no good news from Opera's end for my dev account, my friend told me about this:

https://addons.opera.com/en/extensions/details/install-chrome-extensions/

Let me know if that works for you! It worked for my friend :p

**Comment by Leo-MapCreator** [comment]
omg, its working, i've tried it before but didnt work
thank you so much
