### ISSUE TITLE
Fixes to Chat and Navbar

### ISSUE THREAD

**Issue by Wazarr94** [xenonsb/Haxball-Room-Extension#4]
Hello, once again it's me, I come up with some issues, pretty minor:

1) When hiding Navbar in a room, and you leave and go to another room, the button will say "Hide Navbar" when it's already hidden. Very minor issue

2) For chat, I have seen you decided to be able to quickly reenable it by pressing TAB, which is a very good idea. However, pressing TAB once again doesn't hide it again. Could you fix this also ?

3) I think the delay for the chat to close after pressing Enter is a bit long too, not sure why, but if you can, can you reduce it a bit, ty.

4) The chat button is too big, it is hiding overtime when in overtime, and its name doesn't change. Idea for fix : Change button name to "Enable Chat" and "Disable Chat"

Thanks for the project.

**Comment by xenonsb** [comment]
Most of the listed items will be addressed in the next version.

1. Good catch
2. Use ESC/Enter - since you can tag people using @ then pressing TAB, I can't make the TAB key close the chat in that case.
3. Delay was 250 ms, now set to 200 ms so that you can still see a glimpse of your own message.
4. Changed the text to "Toggle Chat"

**Comment by xenonsb** [comment]
Above fixes incorporated in 0.2.4
